

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class bd_ControlVisitasEntities : DbContext
{
    public bd_ControlVisitasEntities()
        : base("name=bd_ControlVisitasEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<cli_cliente> cli_cliente { get; set; }

    public virtual DbSet<cli_departamento> cli_departamento { get; set; }

    public virtual DbSet<cli_equipo> cli_equipo { get; set; }

    public virtual DbSet<cli_tipoequipo> cli_tipoequipo { get; set; }

    public virtual DbSet<cli_usuario> cli_usuario { get; set; }

    public virtual DbSet<com_usuarios> com_usuarios { get; set; }

    public virtual DbSet<comp_ruta> comp_ruta { get; set; }

    public virtual DbSet<roles> roles { get; set; }

}

}

