//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class cli_cliente
    {
        public cli_cliente()
        {
            this.cli_user = new HashSet<cli_user>();
        }
    
        public int idCli_Cliente { get; set; }

        [Required(ErrorMessage="Campo Obligatorio")]
        [StringLength(100, ErrorMessage = "El campo debe tener por lo menos {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Text)]
        public string Cli_Nombre { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [StringLength(100, ErrorMessage = "El campo debe tener por lo menos {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Text)]
        public string Cli_Ruc { get; set; }
        public string Cli_Direccion { get; set; }
        public string Cli_Tel { get; set; }
        public string Cli_Ciudad { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [StringLength(100, ErrorMessage = "El campo debe tener por lo menos {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Text)]
        public string Cli_RSocial { get; set; }
        public string Cli_NombContacto { get; set; }
    
        public virtual ICollection<cli_user> cli_user { get; set; }
    }
}
