//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cli_usuario
    {
        public int idCli_Usuario { get; set; }
        public string Cli_noombre { get; set; }
        public string Cli_Departamento { get; set; }
        public string Cli_Equipo { get; set; }
        public int Cli_Departamento_idCli_Departamento { get; set; }
        public int Cli_Equipo_idCli_Equipo { get; set; }
        public int Cli_Empresa_idCli_Empresa { get; set; }
    
        public virtual cli_departamento cli_departamento1 { get; set; }
        public virtual cli_empresa cli_empresa { get; set; }
    }
}
