//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class cli_user
    {
        public cli_user()
        {
            this.comp_ruta = new HashSet<comp_ruta>();
        }
    
        public int idCli_Usuario { get; set; }

        [Required(ErrorMessage = "El campo no puede estar vacío.")]
        [StringLength(100, ErrorMessage = "El campo debe contener minimo {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Text)]
        public string Cli_nombre { get; set; }
        public string Cli_apellido { get; set; }

        [EmailAddress]
        public string Cli_Correo { get; set; }
        public int Cli_Equipo_idCli_Equipo { get; set; }
        public int Cli_Equipo_Cli_TipoEquipo_idCli_TipoEquipo { get; set; }
        public int Cli_Cliente_idCli_Cliente { get; set; }
        public int Cli_Departamento_idCli_Departamento { get; set; }
    
        public virtual cli_cliente cli_cliente { get; set; }
        public virtual cli_departamento cli_departamento { get; set; }
        public virtual cli_equipo cli_equipo { get; set; }
        public virtual ICollection<comp_ruta> comp_ruta { get; set; }
    }
}
