//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comp_bitacora
    {
        public int idComp_Bitacora { get; set; }
        public string Comp_Cliente { get; set; }
        public Nullable<System.DateTime> Comp_Fecha { get; set; }
        public string Comp_NumeroVisitaMes { get; set; }
        public string Comp_Equipo { get; set; }
        public string Comp_Usuario { get; set; }
        public string Comp_Informe { get; set; }
    }
}
