//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class roles
    {
        public roles()
        {
            this.com_usuarios = new HashSet<com_usuarios>();
        }
    
        public int idRoles { get; set; }

        [Required(ErrorMessage = "El campo no puede estar vacío.")]
        [StringLength(100, ErrorMessage = "El campo debe contener minimo {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Text)]
        public string Descripcion { get; set; }
    
        public virtual ICollection<com_usuarios> com_usuarios { get; set; }
    }
}
